package main

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
)

func generateAgentID() string {
	b := make([]byte, 8)
	rand.Read(b)
	host, _ := os.Hostname()
	return fmt.Sprintf("%s-%s", host, hex.EncodeToString(b))
}

// Built-in config injected at build time (generated by backend via embed_config.go)
// These are declared here with empty defaults so the agent compiles standalone too.
var (
	builtinToken             string
	builtinAPIBase           string
	builtinHeartbeatInterval int
)

type Config struct {
	APIBase           string `json:"api_base"`
	Token             string `json:"token"`
	HeartbeatInterval int    `json:"heartbeat_interval"`
	AgentVersion      string `json:"agent_version"`
	LogFile           string `json:"log_file"`
	StateFile         string `json:"state_file"`
	MaxLogSize        int64  `json:"max_log_size"`
}

type AgentState struct {
	AgentID string `json:"agentId"`
}

var (
	config     *Config
	configOnce sync.Once
	agentID    string
	agentMu    sync.RWMutex
	startupTS  = now()
)

func defaultConfig() *Config {
	token := os.Getenv("INVISIA_TOKEN")
	if token == "" {
		token = builtinToken
	}

	apiBase := os.Getenv("INVISIA_API")
	if apiBase == "" {
		apiBase = builtinAPIBase
	}
	if apiBase == "" {
		apiBase = "http://localhost:3838/api/agents"
	}

	interval := envIntOrDefault("HEARTBEAT_INTERVAL", 5)
	if interval == 5 && builtinHeartbeatInterval > 0 {
		interval = builtinHeartbeatInterval
	}

	return &Config{
		APIBase:           apiBase,
		Token:             token,
		HeartbeatInterval: interval,
		AgentVersion:      "2.0.0",
		MaxLogSize:        5 * 1024 * 1024,
	}
}

func loadConfigFile(cfg *Config) {
	exe, err := os.Executable()
	if err != nil {
		return
	}
	dir := filepath.Dir(exe)
	configPath := filepath.Join(dir, "config.json")
	data, err := os.ReadFile(configPath)
	if err != nil {
		return
	}
	var fileCfg Config
	if json.Unmarshal(data, &fileCfg) != nil {
		return
	}
	if cfg.Token == "" && fileCfg.Token != "" {
		cfg.Token = fileCfg.Token
	}
	if cfg.APIBase == "" || cfg.APIBase == "http://localhost:3838/api/agents" {
		if fileCfg.APIBase != "" {
			cfg.APIBase = fileCfg.APIBase
		}
	}
	if fileCfg.HeartbeatInterval > 0 {
		cfg.HeartbeatInterval = fileCfg.HeartbeatInterval
	}
}

func GetConfig() *Config {
	configOnce.Do(func() {
		config = defaultConfig()
		loadConfigFile(config)
		exe, _ := os.Executable()
		dir := filepath.Dir(exe)
		if config.LogFile == "" {
			config.LogFile = filepath.Join(dir, "agent.log")
		}
		if config.StateFile == "" {
			config.StateFile = filepath.Join(dir, ".agent-state.json")
		}
	})
	return config
}

func SetAgentID(id string) {
	agentMu.Lock()
	defer agentMu.Unlock()
	agentID = id
	saveStateLocked()
}

func GetAgentID() string {
	agentMu.RLock()
	defer agentMu.RUnlock()
	return agentID
}

func loadState() {
	cfg := GetConfig()
	data, err := os.ReadFile(cfg.StateFile)
	if err != nil {
		return
	}
	var state AgentState
	if json.Unmarshal(data, &state) == nil && state.AgentID != "" {
		agentMu.Lock()
		agentID = state.AgentID
		agentMu.Unlock()
	}
}

func saveStateLocked() {
	cfg := GetConfig()
	state := AgentState{AgentID: agentID}
	data, _ := json.Marshal(state)
	os.WriteFile(cfg.StateFile, data, 0600)
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envIntOrDefault(key string, def int) int {
	if v := os.Getenv(key); v != "" {
		var n int
		if _, err := fmt.Sscanf(v, "%d", &n); err == nil {
			return n
		}
	}
	return def
}
