import { useState, useEffect, useCallback, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { useI18n } from '../i18n/context';
import * as api from '../api/api';
import InfoTooltip from '../components/InfoTooltip';

const I = {
  file: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>,
  spin: <svg className="w-3.5 h-3.5 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>,
  download: <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>,
  check: <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7"/></svg>,
  clock: <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>,
  doc: <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>,
};

function StatCard({ icon, label, value, color = 'var(--text-heading)', sub }) {
  return (
    <div className="rounded-xl border border-border-subtle bg-bg-panel p-5">
      <div className="flex items-center gap-2.5 mb-3">
        <span className="text-text-muted">{icon}</span>
        <span className="text-[10px] text-text-subtle font-medium uppercase tracking-widest">{label}</span>
      </div>
      <p className="text-[26px] font-bold leading-none tracking-tight" style={{ color }}>{value ?? '-'}</p>
      {sub && <p className="text-[10px] text-text-subtle mt-2">{sub}</p>}
    </div>
  );
}

export default function Reports() {
  const { token } = useAuth();
  const { t } = useI18n();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const autoGenerated = useRef(false);

  const fetchReports = useCallback(async () => {
    if (!token) return;
    setError('');
    try {
      const res = await api.getReports(token);
      if (res && !res.error) setReports(Array.isArray(res) ? res : []);
      else setError(res?.error || 'Error al cargar reportes');
    } catch (e) { setError(e.message); }
    finally { setLoading(false); }
  }, [token]);

  useEffect(() => { fetchReports(); }, [fetchReports]);

  useEffect(() => {
    if (!loading && reports.length === 0 && !autoGenerated.current && !generating) {
      autoGenerated.current = true;
      handleGenerate();
    }
  }, [loading, reports, generating]);

  const handleGenerate = async () => {
    setGenerating(true);
    setError('');
    try {
      const res = await api.generateReport(token);
      if (res && !res.error) await fetchReports();
      else setError(res?.error || 'Error al generar reporte');
    } catch (e) { setError(e.message); }
    finally { setGenerating(false); }
  };

  const downloadReport = (id) => {
    window.open(`/api/reports/download/${id}?token=${encodeURIComponent(token)}`, '_blank');
  };

  const downloadAll = () => {
    window.open(`/api/reports/download-all?token=${encodeURIComponent(token)}`, '_blank');
  };

  const formatSize = (bytes) => {
    if (!bytes) return '-';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / 1048576).toFixed(1)} MB`;
  };

  const thisMonth = reports.filter(r => { const d = new Date(r.createdAt); const n = new Date(); return d.getMonth() === n.getMonth() && d.getFullYear() === n.getFullYear(); });
  const thisWeek = reports.filter(r => { const d = new Date(r.createdAt); const n = new Date(); const weekAgo = new Date(n.getTime() - 7 * 86400000); return d >= weekAgo; });

  return (
    <div className="min-h-screen bg-bg-base flex flex-col">
      <header className="sticky top-0 z-30 bg-bg-base border-b border-border-theme flex-shrink-0">
        <div className="flex items-center justify-between px-3 md:px-6 py-3">
          <div className="flex items-center gap-2 md:gap-3 min-w-0">
            <div className="w-8 h-8 rounded-lg bg-bg-elevated border border-border-subtle flex items-center justify-center text-accent shadow-theme-sm">
              {I.doc}
            </div>
            <div>
              <h1 className="text-[12px] md:text-[13px] font-semibold text-text-heading tracking-wide truncate">{t('reports.title') || 'Reportes Automáticos'} <InfoTooltip text="Genera reportes de cumplimiento y seguridad en PDF o CSV para auditorías." placement="right" /></h1>
              <p className="text-[9px] md:text-[10px] text-text-subtle truncate">{t('reports.desc') || 'Generación y descarga de reportes de cumplimiento'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {error && <span className="text-[11px] text-danger hidden md:block">{error}</span>}
            {reports.length > 0 && (
              <button onClick={downloadAll} className="flex items-center gap-1.5 px-2.5 py-1.5 text-[11px] font-medium rounded-lg bg-bg-elevated text-text-muted hover:text-text-body hover:bg-bg-panel transition-all border border-border-subtle">
                {I.download} Descargar Todos <InfoTooltip text="Descarga todos los reportes generados como archivo ZIP." placement="left" />
              </button>
            )}
            <button onClick={handleGenerate} disabled={generating}
              className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-medium rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-theme-sm">
              {generating ? (
                <>{I.spin} Generando...</>
              ) : (
                <>{I.file} Generar Reporte</>
              )}
              <InfoTooltip text="Genera un nuevo reporte de cumplimiento y seguridad." placement="left" />
            </button>
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto theme-scrollbar">
        <div className="p-3 md:p-6 max-w-7xl mx-auto">
          {loading ? (
            <div className="flex items-center justify-center h-40">
              <div className="w-5 h-5 border-2 border-accent border-t-transparent rounded-full animate-spin" />
            </div>
          ) : reports.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-72">
              <div className="w-16 h-16 rounded-2xl bg-bg-elevated border border-border-subtle flex items-center justify-center mb-5 shadow-theme-sm">
                <svg className="w-7 h-7 text-text-muted" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                </svg>
              </div>
              <p className="text-[13px] font-medium text-text-muted mb-1">No hay reportes generados</p>
              <p className="text-[11px] text-text-subtle mb-6 max-w-[280px] text-center">Genera tu primer reporte de cumplimiento Ley 21.719</p>
              <button onClick={handleGenerate} disabled={generating}
                className="px-5 py-2 rounded-lg text-[12px] font-medium bg-emerald-600 hover:bg-emerald-500 text-white transition-all disabled:opacity-50 flex items-center gap-2 shadow-theme-sm">
                {generating ? <>{I.spin} Generando...</> : <>{I.file} Generar Reporte</>}
                <InfoTooltip text="Genera un nuevo reporte de cumplimiento y seguridad." placement="right" />
              </button>
            </div>
          ) : (
            <div className="space-y-4 md:space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 md:gap-5 tour-detail-1">
                <StatCard icon={I.doc} label={<>Total Reportes <InfoTooltip text="Número total de reportes generados en el sistema." placement="top" /></>} value={reports.length} color="var(--text-heading)" sub={`${thisMonth.length} este mes`} />
                <StatCard icon={I.clock} label={<>Reportes Este Mes <InfoTooltip text="Reportes generados en el mes actual." placement="top" /></>} value={thisMonth.length} color="#22d3ee" sub={thisWeek.length > 0 ? `${thisWeek.length} esta semana` : ''} />
                <StatCard icon={I.check} label={<>Último Reporte <InfoTooltip text="Fecha y hora del reporte más reciente." placement="top" /></>} value={reports[0] ? new Date(reports[0].createdAt).toLocaleDateString('es', { year: 'numeric', month: 'short', day: 'numeric' }) : '-'} color="#22c55e" sub={reports[0] ? new Date(reports[0].createdAt).toLocaleTimeString('es', { hour: '2-digit', minute: '2-digit' }) : ''} />
              </div>

              <div className="rounded-xl border border-border-subtle bg-bg-panel overflow-hidden shadow-theme-sm tour-detail-2">
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="bg-bg-elevated/40">
                        <th className="text-[10px] uppercase tracking-wider text-text-muted font-semibold py-3 px-4 text-left">Título <InfoTooltip text="Nombre descriptivo del reporte generado." placement="top" /></th>
                        <th className="text-[10px] uppercase tracking-wider text-text-muted font-semibold py-3 px-4 text-left">Tipo <InfoTooltip text="Categoría del reporte: cumplimiento, mensual o auditoría." placement="top" /></th>
                        <th className="text-[10px] uppercase tracking-wider text-text-muted font-semibold py-3 px-4 text-left">Fecha <InfoTooltip text="Fecha y hora de generación del reporte." placement="top" /></th>
                        <th className="text-[10px] uppercase tracking-wider text-text-muted font-semibold py-3 px-4 text-right">Tamaño <InfoTooltip text="Tamaño del archivo del reporte en disco." placement="top" /></th>
                        <th className="text-[10px] uppercase tracking-wider text-text-muted font-semibold py-3 px-4 text-center">Descargar <InfoTooltip text="Descarga el reporte en formato PDF." placement="top" /></th>
                      </tr>
                    </thead>
                    <tbody>
                      {reports.map((r) => (
                        <tr key={r._id} className="hover:bg-bg-elevated/30 transition-all duration-200 border-t border-border-subtle">
                          <td className="py-3.5 px-4">
                            <p className="text-[12px] text-text-heading font-medium truncate max-w-[300px]">{r.title}</p>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className={`inline-flex items-center gap-1 px-2 py-0.5 text-[10px] font-semibold rounded-md ${
                              r.type === 'compliance' ? 'bg-emerald-500/10 text-emerald-500' :
                              r.type === 'monthly' ? 'bg-indigo-500/10 text-indigo-500' :
                              r.type === 'annual' ? 'bg-amber-500/10 text-amber-500' :
                              r.type === 'audit' ? 'bg-rose-500/10 text-rose-500' :
                              'bg-blue-500/10 text-blue-500'
                            }`}>
                              {r.type === 'compliance' ? 'Cumplimiento' : r.type === 'monthly' ? 'Mensual' : r.type === 'annual' ? 'Anual' : r.type === 'audit' ? 'Auditoría' : r.type}
                            </span>
                          </td>
                          <td className="py-3.5 px-4">
                            <span className="text-[11px] text-text-muted">{new Date(r.createdAt).toLocaleDateString('es', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
                          </td>
                          <td className="py-3.5 px-4 text-right text-[11px] text-text-muted">{formatSize(r.fileSize)}</td>
                          <td className="py-3.5 px-4 text-center">
                            <button onClick={() => downloadReport(r._id)}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[11px] font-medium bg-accent-subtle text-accent hover:bg-accent hover:text-white transition-all">
                              {I.download} PDF <InfoTooltip text="Descarga este reporte individual en formato PDF." placement="left" />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
